### ISSUE TITLE
Translation and Rotate

### ISSUE THREAD

**Issue by JiayiLy** [koyeongmin/PINet_new#10]
Hi, I have some question about Translation and Rotate in data_loader.py.
[https://github.com/koyeongmin/PINet_new/blob/fead6baf0210a11444bf02d8fda7b3a33cec8e8c/TuSimple/data_loader.py#L384](url)
Why don't you process target_h when you translate and rotate the image in case that target_h is out of [0, y_size-1]?

**Comment by koyeongmin** [comment]
Because y_size is height of input image, It will occur error if we make some value at that point.

**Comment by JiayiLy** [comment]
Probably I didn't make myself clear to you. When you translate and rotate the image, why don't you translate and rotate the target_h that is y coordinates of lane keypoints? In your code, you only translate and rotate target_lanes that is x coordinates of lane keypoints.
