### ISSUE TITLE
About data augmentation ‘Change_intensity’?

### ISSUE THREAD

**Issue by JiayiLy** [koyeongmin/PINet_new#15]
In the 'Change_intensity' data augmentation, you only change the v channel values in hsv color space. Could you please tell me how useful is this operation for the performance?

**Comment by koyeongmin** [comment]
TuSImple and CULane datasets include tunnel or night environments. In these environments, input images are very dark, so I added the augmentation method.

**Comment by JiayiLy** [comment]
Thank you for your kind reply
