### ISSUE TITLE
Frame rate of the video

### ISSUE THREAD

**Issue by dkhanna511** [koyeongmin/PINet_new#18]
When I test the model on mode 1, the frame rate of the output video is significantly low as compared to the input video. What changes do I need to do to increase the frame rate of the output videos or for real-time testing on the road.

**Comment by koyeongmin** [comment]
4 hourglass model shows about 25 fps on RTX2080ti. You can increase speed by clip some hourglass networks

**Comment by dkhanna511** [comment]
Thanks!
