### ISSUE TITLE
why do you remove eliminate_out function in post-processing?

### ISSUE THREAD

**Issue by sigma-alpha-beta** [koyeongmin/PINet_new#27]
I found that post processing for eliminating outliers is removed, can you tell me what's wrong with this function, thank you

**Comment by koyeongmin** [comment]
The post-processing is very slow but it shows a little improvement. In PINet_new, the post-processing is replaced with spline fitting, spline fitting shows a good performance. Thank you!

**Comment by sigma-alpha-beta** [comment]
thanks for your answer!
