### ISSUE TITLE
Questions about data normalization

### ISSUE THREAD

**Issue by garryz94** [koyeongmin/PINet_new#4]
hi @koyeongmin thanks for your execellent work, it's really impressive!
I noticed that you didn't do data normalization like `data=(data-mean)/stddev`. Is it better to normalize data or do batchnorm at the input layer?

**Comment by garryz94** [comment]
FYI,[ huawei-noah](https://github.com/xbjxh/CurveLanes) just published a novel dataset called CurveLanes for detecting curved lanes in images. Maybe you can train model on this dataset. I think the idea of PINet is quite suitable for curved lane detection.

**Comment by koyeongmin** [comment]
For normalization, I just apply dividing by 255(maximum of pixel values). I couldn't try other normalization method... CurveLanes looks good dataset! I will try soon! Thank you!

**Comment by garryz94** [comment]
> For normalization, I just apply dividing by 255(maximum of pixel values). I couldn't try other normalization method... CurveLanes looks good dataset! I will try soon! Thank you!

I am trying to train PINet on Curvelanes now. Any progress on this dataset will be updated here!

**Comment by koyeongmin** [comment]
Thank you!

**Comment by gneworld** [comment]
@garryz94  do you have any update info about training PINet on Curvelanes now? thanks

**Comment by gneworld** [comment]
@garryz94  do you have any update info about training PINet on Curvelanes now? thanks

**Comment by gneworld** [comment]
@garryz94  do you have any update info about training PINet on Curvelanes now? thanks

**Comment by gneworld** [comment]
@garryz94  do you have any update info about training PINet on Curvelanes now? thanks

**Comment by gneworld** [comment]
@garryz94  do you have any update info about training PINet on Curvelanes now? thanks

**Comment by garryz94** [comment]
> @garryz94 do you have any update info about training PINet on Curvelanes now? thanks

@gneworld Sorry I've been busy for other things recently. Please let me know if you have any progress on this dataset.
