### ISSUE TITLE
generate result problem

### ISSUE THREAD

**Issue by NEFUtraffica** [koyeongmin/PINet_new#51]

**Comment by koyeongmin** [comment]
Hi! This is my mistake. I didn't implement the code to adjust the percentage when the batch size is changed. But the code will evaluate for whole dataset regardless of the percentage. Thank you!

**Comment by NEFUtraffica** [comment]
batch_size = self.p.batch_size
cuts = [(i * batch_size, (i + 1) * batch_size) for i in range(self.size_test // batch_size)]
if self.size_test % batch_size != 0:
    cuts.append((cuts[-1][1], self.size_test))

for start, end in cuts:
    progressbar.update(1)Thank you very much for your answer, this is my modified code, can you see if this is okay, very much hope to continue to communicate with you, thank you!

**Comment by NEFUtraffica** [comment]
Thank you very much for your answer, this is my modified code, can you see if this is okay, very much hope to continue to communicate with you, thank you!

**Comment by NEFUtraffica** [comment]
> Hi! This is my mistake. I didn't implement the code to adjust the percentage when the batch size is changed. But the code will evaluate for whole dataset regardless of the percentage. Thank you!
Thank you very much for your answer, this is my modified code, can you see if this is okay, this is the Generate code in the data_lodaer, very much hope to continue to communicate with you, thank you!

batch_size = self.p.batch_size
cuts = [(i * batch_size, (i + 1) * batch_size) for i in range(self.size_test // batch_size)]
if self.size_test % batch_size != 0:
    cuts.append((cuts[-1][1], self.size_test))
for start, end in cuts:

    progressbar.update(1)
